spring:
  datasource:
    url: jdbc:mysql://localhost.mysql:3306/demo_security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

###################################### MyBatis 配置######################################
mybatis-plus:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.example.demo.uac.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true